---
environment: test
server:
  port: 4000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer
varTree:
  welcomeMsg: hello from test
---
environment: prod
server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowopendev
    username: developer
    password: developer
varTree:
  welcomeMsg: hello from prod


